const header=document.querySelector("#site-header"),menu=document.querySelector(".menu-button"),mobile=document.querySelector(".mobile-nav"),cursor=document.querySelector(".cursor"),sections=[...document.querySelectorAll("main section[id]")],links=[...document.querySelectorAll(".desktop-nav a,.mobile-nav a")];
document.querySelector("#year").textContent=new Date().getFullYear();
menu.addEventListener("click",()=>{const open=menu.classList.toggle("open");mobile.classList.toggle("open",open);document.body.classList.toggle("menu-open",open);menu.setAttribute("aria-expanded",String(open));menu.setAttribute("aria-label",open?"Close menu":"Open menu")});
mobile.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>{menu.classList.remove("open");mobile.classList.remove("open");document.body.classList.remove("menu-open");menu.setAttribute("aria-expanded","false")}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});
document.querySelectorAll(".reveal").forEach(element=>observer.observe(element));
const update=()=>{header.classList.toggle("scrolled",scrollY>30);const marker=scrollY+innerHeight*.3;let current="";sections.forEach(section=>{if(marker>=section.offsetTop)current=section.id});links.forEach(link=>link.classList.toggle("active",link.getAttribute("href")===`#${current}`))};
addEventListener("scroll",update,{passive:true});update();
if(matchMedia("(hover:hover) and (pointer:fine)").matches){addEventListener("mousemove",event=>{cursor.style.left=`${event.clientX}px`;cursor.style.top=`${event.clientY}px`});document.querySelectorAll("a,button").forEach(element=>{element.addEventListener("mouseenter",()=>cursor.classList.add("hover"));element.addEventListener("mouseleave",()=>cursor.classList.remove("hover"))})}
